services:
  frontend:
    container_name: react-app-dev
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules  # Prevents node_modules from being overwritten
    ports:
      - "3000:3000"
    command: npm run dev
