services:
  frontend:
    container_name: react-app-dev
    build:
      context: .
    env_file:
      - ".env.development.local"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # Prevents node_modules from being overwritten
    ports:
      - "5173:5173"
    command: npm run start
