services:
  react-app:
    image: "node:23.7.0"
    working_dir: /home/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./app/:/home/app
    expose:
      - "3000"
    ports: # use if it is necessary to expose the container to the host machine
      - "3000:3000"
    command: "npm i; npm start"
