name: Automated Tests

on:
  push:
    branches-ignore:
      - 'gh-pages'

jobs:
  build:
    name: Build and Type Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build --if-present

      - name: Type Check
        run: npm run typecheck

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm run test:no-watch
