name: CI for TypeScript/React App

on:
  push

jobs:
  build:
    name: Build and Type Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'

      - name: Install dependencies
        run: cd app && npm install

      - name: Build and Type Check (Strict Mode)
        run: cd app && npm run build --if-present && npm run typecheck

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'

      - name: Install dependencies
        run: cd app && npm install

      - name: Run Tests
        run: cd app && npm test -- --watchAll=false --ci
